.MODEL SMALL
DISPLAY MACRO MSG
LEA DX, MSG
MOV AH, 09H
INT 21H
ENDM
.DATA
LIST DB 03H, 07H, 01H, 09H
KEY DB 03H
MSG1 DB 0DH, 0AH, "ELEMENT FOUND IN THE LIST...$"
MSG2 DB 0DH, 0AH, "SEARCH FAILED..$"
.CODE SEGMENT
ASSUME CS:CODE, DS:DATA
START:MOV AX, DATA
      MOV DS, AX
      MOV AL, SE
      LEA SI, LIST
      MOV CX, 04H
 UP: MOV BL, [SI]
     CMP AL, BL
     JZ FO
     INC SI
     DEC CX
     JNZ UP
     MACRO MSG2
     JMP END1

 FO: MACRO MSG1

 END1:
   INT 3
   END START
